apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "s3-nginx-ingress.fullname" . }}-config
  labels:
    {{- include "s3-nginx-ingress.labels" . | nindent 4 }}
data:
  S3_BUCKET_NAME: {{ .Values.s3.bucketName | quote }}
  AWS_REGION: {{ .Values.aws.region | quote }}
